version: '3.8'

services:
  postgres:
    image: postgres #hub.docker.com se is image ko pull krega
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password
  
  redis :
    image: redis # again this image will be pulled from hub.docker.com
    ports :
      - "6379:6379"
